Enhance GitHub Actions workflow with Docker support

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,16 +1,38 @@
 name: Main workflow
+
 on: push
+
+env:
+  github_username: artemziablov
+  github_password: ${{ secrets.GITHUB_TOKEN }}
+  GIT_COMMIT: ${{ github.sha }}
+
 jobs:
   Build:
     runs-on: ubuntu-latest
     container: gradle:6-jdk11
+
     steps:
+      - name: Validate GitHub username is all lowercase
+        id: validate_lower
+        run: |
+          if [[ "${{ env.github_username }}" =~ [A-Z] ]]; then
+            echo "::error::Validation Failed: GitHub username '${{ env.github_username }}' cannot contain uppercase characters."
+            exit 1
+          else
+            echo "GitHub username format is valid."
+          fi
+        shell: bash
+
       - name: Clone down repository
         uses: actions/checkout@v4
+
       - name: Build application
         run: ci/build-app.sh
+
       - name: Test
         run: ci/unit-test-app.sh
+
       - name: Upload repo
         uses: actions/upload-artifact@v4
         with:
@@ -20,17 +42,40 @@ jobs:
 
   Linting:
     runs-on: ubuntu-latest
-    needs: [Build]
+    needs:
+      - Build
+
     steps:
       - name: Download code
         uses: actions/download-artifact@v4
         with:
           name: code
           path: .
+
       - name: run linting
         uses: super-linter/super-linter/slim@v7
         env:
           DEFAULT_BRANCH: main
-          # To report GitHub Actions status checks
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           DISABLE_ERRORS: true
+
+  Docker-image:
+    runs-on: ubuntu-latest
+    needs:
+      - Build
+    permissions:
+      contents: read
+      packages: write
+
+    steps:
+      - name: Download code
+        uses: actions/download-artifact@v4
+        with:
+          name: code
+          path: .
+
+      - name: build docker
+        run: bash ci/build-docker.sh
+
+      - name: push docker
+        run: bash ci/push-docker.sh
